name: Deploy to prod

on:
  push:
    tags:
      - prod

env:
  AZURE_FUNCTIONAPP_NAME: "haasteikkoprod-flex-api-mfi6ibzdnrl7i"
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./backend/deployment"
  AZURE_STORAGE_ACCOUNT_NAME: "haasteikkoprodhsmfi6ibz"
  AZURE_EXTERNAL_TENANT_ID: "598750cd-d651-40f0-a8ba-dc7d2409b558"
  AZURE_EXTERNAL_CLIENT_ID: "7026c030-9feb-4589-b17f-cc27c5cacb6d"
  API_URL: "https://haasteikkoprod-flex-api-mfi6ibzdnrl7i.azurewebsites.net/api"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
          cache-dependency-path: |
            backend/go.sum

      - name: Build backend binary
        run: |
          cd backend
          go mod download
          go mod tidy
          GOOS=linux GOARCH=amd64 go build -o backend
          mkdir -p deployment
          mv backend deployment/backend
          cp -r api deployment/
          cp host.json deployment/host.json

          cd deployment

          sed -i 's/\.exe//g' host.json

      - name: "Deploy backend to Azure Functions"
        uses: "Azure/functions-action@v1"
        id: functions-deployment
        with:
          sku: "flexconsumption"
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Build frontend
        env:
          VITE_API_URL: ${{ env.API_URL }}
          VITE_CLIENT_ID: ${{ env.AZURE_EXTERNAL_CLIENT_ID }}
          VITE_TENANT_ID: ${{ env.AZURE_EXTERNAL_TENANT_ID }}
          VITE_REDIRECT_URI: https://haasteikkoprodhsmfi6ibz.z1.web.core.windows.net/auth/callback
          VITE_POST_LOGOUT_REDIRECT_URI: https://haasteikkoprodhsmfi6ibz.z1.web.core.windows.net
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob service-properties update --account-name  ${{ env.AZURE_STORAGE_ACCOUNT_NAME }} --static-website --404-document index.html --index-document index.html --auth-mode key
            az storage blob sync -c \$web --account-name ${{ env.AZURE_STORAGE_ACCOUNT_NAME }} --auth-mode key -s ./frontend/dist

        # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
